# Fictional Army - Filtering and Sorting

### Introduction:

This exercise was inspired by this [page](http://chrisalbon.com/python/)

Special thanks to: https://github.com/chrisalbon for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [18]:
import pandas as pd

### Step 2. This is the data given as a dictionary

In [30]:
data = {
    'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons'],
    'company': ['1st', '2nd', '3rd', '4th', '1st', '2nd', '3rd', '4th'],
    'deaths': [51, 34, 65, 25, 48, 52, 66, 32],
    'battles': [5, 3, 6, 3, 7, 8, 5, 6],
    'size': [1045, 834, 913, 721, 982, 1023, 876, 765],
    'veterans': [1, 4, 5, 2, 3, 4, 3, 2],
    'readiness': ['yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes'],
    'deserters': [5, 2, 1, 3, 2, 3, 4, 1],  # ← THIS WAS MISSING
    'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington']
}

### Step 3. Create a dataframe and assign it to a variable called army. 

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

In [31]:
army = pd.DataFrame(data, columns=['regiment', 'company', 'deaths', 'battles', 'size', 'veterans', 'readiness', 'deserters', 'origin'])

In [22]:
army = pd.DataFrame(data, columns=['regiment', 'company', 'deaths', 'battles', 'size', 'veterans', 'readiness', 'origin'])

### Step 4. Set the 'origin' colum as the index of the dataframe

In [32]:
army.set_index('origin', inplace=True)

### Step 5. Print only the column veterans

In [24]:
army['veterans']

origin
Arizona       1
California    4
Texas         5
Florida       2
Maine         3
Iowa          4
Alaska        3
Washington    2
Name: veterans, dtype: int64

### Step 6. Print the columns 'veterans' and 'deaths'

In [25]:
army[['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1      51
California         4      34
Texas              5      65
Florida            2      25
Maine              3      48
Iowa               4      52
Alaska             3      66
Washington         2      32

### Step 7. Print the name of all the columns.

In [26]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness'],
      dtype='str')

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [28]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness'],
      dtype='str')

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [33]:
army.iloc[3:8, 3:7]

            battles  size  veterans readiness
origin
Florida           3   721         2        no
Maine             7   982         3       yes
Iowa              8  1023         4        no
Alaska            5   876         3        no
Washington        6   765         2       yes

### Step 10. Select every row after the fourth row and all columns

In [36]:
army.iloc[4:]

,regiment,company,deaths,battles,size,veterans,readiness,deserters
origin,,,,,,,,
Maine,Dragoons,1st,48,7,982,3,yes,2
Iowa,Dragoons,2nd,52,8,1023,4,no,3
Alaska,Dragoons,3rd,66,5,876,3,no,4
Washington,Dragoons,4th,32,6,765,2,yes,1

Select## Step 11.  every row up to the 4th row and all columns

In [40]:
army.iloc[:4]

,regiment,company,deaths,battles,size,veterans,readiness,deserters
origin,,,,,,,,
Arizona,Nighthawks,1st,51,5,1045,1,yes,5
California,Nighthawks,2nd,34,3,834,4,no,2
Texas,Nighthawks,3rd,65,6,913,5,yes,1
Florida,Nighthawks,4th,25,3,721,2,no,3

### Step 12. Select the 3rd column up to the 7th column

In [43]:
army.iloc[:, 2:7]

            deaths  battles  size  veterans readiness
origin
Arizona         51        5  1045         1       yes
California      34        3   834         4        no
Texas           65        6   913         5       yes
Florida         25        3   721         2        no
Maine           48        7   982         3       yes
Iowa            52        8  1023         4        no
Alaska          66        5   876         3        no
Washington      32        6   765         2       yes

### Step 13. Select rows where df.deaths is greater than 50

In [42]:
army[army['deaths'] > 50]

,regiment,company,deaths,battles,size,veterans,readiness,deserters
origin,,,,,,,,
Arizona,Nighthawks,1st,51,5,1045,1,yes,5
Texas,Nighthawks,3rd,65,6,913,5,yes,1
Iowa,Dragoons,2nd,52,8,1023,4,no,3
Alaska,Dragoons,3rd,66,5,876,3,no,4

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [41]:
army[(army['deaths'] > 500) | (army['deaths'] < 50)]

,regiment,company,deaths,battles,size,veterans,readiness,deserters
origin,,,,,,,,
California,Nighthawks,2nd,34,3,834,4,no,2
Florida,Nighthawks,4th,25,3,721,2,no,3
Maine,Dragoons,1st,48,7,982,3,yes,2
Washington,Dragoons,4th,32,6,765,2,yes,1

### Step 15. Select all the regiments not named "Dragoons"

### Step 16. Select the rows called Texas and Arizona

### Step 17. Select the third cell in the row named Arizona

### Step 18. Select the third cell down in the column named deaths

In [ ]:
army.iloc[2, 2]